Update CHANGELOG.md
helpscout/beacon-ios-sdk pull request #175
Opened 2022-02-25 18:49 UTC by adrianne-helpscout

Adding a note to the changelog about our move from support via GitHub Issues to our customer support queue.

2022-02-25 20:03 UTC, keishaj-creates reviewed
Do we need to change the date from Feb 4 to today?

2022-02-25 20:16 UTC, ScottPetit requested changes
It seems like the intent of this was to align the "Not a new release" paragraph below the `Change to developer support` section.  It seems to have snuck in under the 2.2.4 release section though.

2022-02-25 20:16 UTC, ScottPetit commented on CHANGELOG.md
> +
```suggestion
Not a new release, per se, but we have migrated support from GitHub Issues in this repository to our customer support team. Links in earlier changelog entries that pointed to an issue will no longer work, you will get a 404 when following them. For additional information on a previous release, github issue, or any other request for support please reach out to us via [help@helpscout.com](mailto:help@helpscout.com?subject=%5BiOS%20Beacon%20SDK%5D%20Issue%20report&body=Technical%20details%0A%0A-%20Beacon%20version%3A%0A-%20iOS%20OS%20version%3A%0A-%20Device%20make%2Fmodel%3A%0A-%20Impacted%20user%20count%3A%0A%0AActual%20outcome%0A%0A%20%20%20%20Beacon%20did%20or%20did%20not...%0A%0AExpected%20outcome%0A%0A%20%20%20%20Beacon%20should...%0A%0ASteps%20to%20reproduce%0A%0A%20%20%20%201.%20%E2%80%A6%0A%20%20%20%202.%20%E2%80%A6%0A%20%20%20%203.%20%E2%80%A6%0A%0AScreenshots%2FScreen%20Recording%0A%0A%20%20%20%20Please%20add%20any%20images%20or%20videos%20to%20support%20your%20report.%0A%0AAdditional%20Information%0A%0A%20%20%20%20Please%20attach%20any%20crash%20logs)

```

2022-02-26 01:09 UTC, adrianne-helpscout commented
@keishaj-creates We made the change on Feb 4th; so, I think best to leave that as the date.

2022-02-28 13:09 UTC, ScottPetit approved these changes
Looks good to me.

2022-02-28 13:21 UTC, keishaj-creates approved these changes

2022-02-28 18:09 UTC, merged